default:
  data: "segmented-data.csv"
  data_covariates: "segmented-data-covariates.csv"
  target_data_analysis: "data_analysis"

dev:
  target_data_analysis: "data_analysis_dev"

test:
  target_data_analysis: "data_analysis_test"
